title: Finch
optionalCategoryIndex: true
supportedLanguages: []
properties: []
link:
  name: Finch_help
  pathname: github.com/Smile-Tech-Study/Finch_help/main/-
  lastVisited: github.com/Smile-Tech-Study/Finch_help/main/-/README
  logo: Finch.svg
  title: Finch
  query: {}
  group: null
  code: ""
  style: null
  description: null
  order: 999999
  isCloning: false
  cloneCancelDisabled: false
  redirectOnClone: null
relatedLinks: []
name: Finch_help
repositoryName: Finch_help
sourceName: github.com
userInfo:
  mail: kitlove51@list.ru
  name: LyubovAsseyeva
  id: kitlove51@list.ru
logo: logo (1).png
logo_dark: logo (2).png
