title: Finch
optionalCategoryIndex: true
supportedLanguages: []
properties: []
link:
  name: Finch_help
  pathname: github.com/Smile-Tech-Study/Finch_help/main/-
  lastVisited: >-
    github.com/Smile-Tech-Study/Finch_help/main/-/podrobnee-obo-vsekh-obnovleniyakh/demonstraciya-so-zvukom
  logo: null
  title: Finch
  query: {}
  group: null
  code: ""
  style: null
  description: null
  order: 999999
  isCloning: false
  cloneCancelDisabled: false
  redirectOnClone: null
relatedLinks: []
name: Finch_help
repositoryName: Finch_help
sourceName: github.com
userInfo:
  mail: kitlove51@list.ru
  name: LyubovAsseyeva
  id: kitlove51@list.ru
logo: Finch.svg
logo_dark: Для+загрузки+(1) (1).svg
